version: "3.9"

services:
  front:
    image: Tvitser/Cource_7:base
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: Tvitser/Cource_7:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_heathy
      migrations:
        condition: service_completed_succesfully
    volumes:
      - ./.env:/app/.env
  mirations:
    image: Tvitser/Cource_7:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      - postgres:
          condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER44
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data