version:"3.9"

services:
  front:
    build:
      dockerfile: Dockerfile
      context: front
    ports:
      - 8034:80
    depends_on:
      - api
  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_heathy
      migrations:
        condition: service_completed_succesfully
    volumes:
      - ./.docker_env:/app/.env
  mirations:
    build:
      context: .
    depends_on:
      - postgres:
          condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data